# Generated by Django 3.2.15 on 2022-09-16 14:06

from django.db import migrations, models
from config.settings import base

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        (migrations.swappable_dependency(base.AUTH_USER_MODEL))
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
